import Foundation
import Network
#if HERMIT_EMBEDDED_SERVER
import HermitServer
#endif

// MARK: - hermit-y9x: Launch embedded Go server at app startup
// MARK: - hermit-6et: Register Bonjour _hermit._tcp service after server starts

/// Manages the lifecycle of the embedded Hermit Go server on macOS.
///
/// On macOS the Go server is compiled into HermitServer.xcframework via
/// `make gomobile-build` and linked into the macOS target only.
/// EmbeddedServerManager starts it at app launch, surfaces the bound port
/// to AppState, and registers a Bonjour NWListener so nearby iPads can
/// discover this Mac via Mode 2 (local network).
///
/// To enable the embedded server, add `-DHERMIT_EMBEDDED_SERVER` to Swift
/// Other Flags in Xcode Build Settings (macOS target only) after running
/// `make gomobile-build` to produce HermitServer.xcframework.
///
/// Requires entitlements:
///   com.apple.security.network.server  — to bind a TCP port
///   com.apple.security.network.client  — to make outbound HTTP calls
#if os(macOS)
@MainActor
final class EmbeddedServerManager: ObservableObject {

    static let shared = EmbeddedServerManager()

    @Published private(set) var port: Int? = nil
    @Published private(set) var errorMessage: String? = nil

    private var bonjourListener: NWListener? = nil

    private init() {}

    // MARK: - Start

    /// Starts the embedded Go server and registers Bonjour.
    /// When HERMIT_EMBEDDED_SERVER is set, calls the HermitServer.xcframework's
    /// `MobileStart(_:)` export generated by `gomobile bind`.
    /// Without the flag (CI, development without xcframework) this is a no-op.
    func start(appState: AppState) {
        guard port == nil else { return }

#if HERMIT_EMBEDDED_SERVER
        let config = buildConfigJSON(appState: appState)

        // MobileStart / MobileStop are generated by gomobile bind from mobile.Start()/Stop().
        // MobileStart returns either "<port>" or "error: <message>".
        let result = MobileStart(config)

        if result.hasPrefix("error:") {
            errorMessage = result
            return
        }
        guard let p = Int(result) else {
            errorMessage = "embedded server returned unexpected port: \(result)"
            return
        }

        port = p
        errorMessage = nil
        appState.serverBaseURL = "http://127.0.0.1:\(p)"
        registerBonjour(port: p)
#else
        // xcframework not yet built — server unavailable in this build.
        // Run `make gomobile-build` and add -DHERMIT_EMBEDDED_SERVER to enable.
        errorMessage = "Embedded server not available: run make gomobile-build first."
#endif
    }

    // MARK: - Stop

    /// Gracefully stops the server and tears down Bonjour.
    func stop() {
        bonjourListener?.cancel()
        bonjourListener = nil
#if HERMIT_EMBEDDED_SERVER
        MobileStop()
#endif
        port = nil
    }

    // MARK: - Bonjour advertising (hermit-6et)

    private func registerBonjour(port: Int) {
        guard let nwPort = NWEndpoint.Port(rawValue: UInt16(port)) else { return }

        do {
            let listener = try NWListener(using: .tcp, on: nwPort)
            listener.service = NWListener.Service(
                name: "Hermit",
                type: "_hermit._tcp",
                txtRecord: NWTXTRecord(["version": "1"])
            )
            listener.stateUpdateHandler = { state in
                switch state {
                case .failed(let error):
                    print("[EmbeddedServerManager] Bonjour listener failed: \(error)")
                default:
                    break
                }
            }
            listener.newConnectionHandler = { connection in
                // Only need the advertisement; reject connections on this listener
                // (real API traffic goes to the Go server's port).
                connection.cancel()
            }
            listener.start(queue: .main)
            bonjourListener = listener
        } catch {
            print("[EmbeddedServerManager] Failed to create Bonjour listener: \(error)")
        }
    }

    // MARK: - Config JSON

    private func buildConfigJSON(appState: AppState) -> String {
        let dataDir = Self.appSupportDirectory()
        let payload: [String: String] = [
            "baseURL":  appState.baseURL,
            "pat":      appState.pat,
            "owner":    appState.repoOwner,
            "repo":     appState.repoName,
            "docsPath": appState.docsPath,
            "rfcLabel": appState.rfcLabel,
            "dataDir":  dataDir,
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: payload),
              let str  = String(data: data, encoding: .utf8) else {
            return "{}"
        }
        return str
    }

    private static func appSupportDirectory() -> String {
        let urls = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)
        return urls.first?.appendingPathComponent("Hermit").path ?? NSHomeDirectory()
    }
}
#endif
