environment: development
listen_address: ":8080"
cache:
  repository_rfc_list:
    read_ttl: 3m
    jitter: 1m
registries:
  - name: github
    kind: github
    base_url: https://api.github.com
  - name: github-enterprise
    kind: github
    base_url: https://github.ibm.com/api/v3
  - name: gitea-local
    kind: github
    base_url: http://localhost:3000/api/v1
repositories:
#  - owner: hashicorp
#    name: agx-bridge
#    registry: github
#    default_branch: main
#    docs_path_policy: docs-cms/rfcs/
#  - owner: Steven-Taylor1
#    name: hermit
#    registry: github-enterprise
#    default_branch: main
#    docs_path_policy: docs-cms/rfcs/
  - owner: gitea_admin
    name: hermit-rfcs
    registry: gitea-local
    default_branch: main
    docs_path_policy: docs-cms/rfcs/
