environment: development
listen_address: ":8080"
registries:
  - name: github-public
    kind: github
    base_url: https://api.github.com
  - name: github-enterprise
    kind: github
    base_url: https://github.example.com/api/v3
  - name: gitea-local
    kind: github
    base_url: http://localhost:3000/api/v1
repositories:
  - owner: hashicorp
    name: hermit
    registry: github-public
    default_branch: main
    docs_path_policy: docs-cms/rfcs/
  - owner: acme
    name: platform-rfcs
    registry: github-enterprise
    default_branch: trunk
    docs_path_policy: docs-cms/rfcs/
  - owner: gitea_admin
    name: hermit-rfcs
    registry: gitea-local
    default_branch: main
    docs_path_policy: docs-cms/rfcs/
