#!/bin/sh
# ci_post_clone.sh — runs on Xcode Cloud after repo clone, before build.
#
# Generates hermit-native/Local.xcconfig from Xcode Cloud environment variables.
# Set HERMIT_TEAM_ID and HERMIT_BUNDLE_ID in:
#   App Store Connect → Xcode Cloud → Workflows → Environment

set -e

# Resolve Local.xcconfig path relative to this script's location.
# The script lives at hermit-native/ci_scripts/, so one level up is hermit-native/.
# This avoids any dependency on CI_WORKSPACE which is not set during post-clone.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
XCCONFIG="$SCRIPT_DIR/../Local.xcconfig"

: "${HERMIT_TEAM_ID:?HERMIT_TEAM_ID must be set in Xcode Cloud workflow environment}"
: "${HERMIT_BUNDLE_ID:?HERMIT_BUNDLE_ID must be set in Xcode Cloud workflow environment}"

cat > "$XCCONFIG" <<EOF
// Auto-generated by ci_scripts/ci_post_clone.sh — do not commit.
HERMIT_TEAM_ID = ${HERMIT_TEAM_ID}
HERMIT_BUNDLE_ID = ${HERMIT_BUNDLE_ID}
EOF

echo "ci_post_clone: wrote Local.xcconfig (team=${HERMIT_TEAM_ID} bundle=${HERMIT_BUNDLE_ID})"
